/**
 * Prisma type re-exports for @syntaxure-labs/db consumers.
 *
 * These types are generated by `prisma generate` and are the single source of
 * truth for the database schema. Apps should import from here instead of
 * hand-maintained database.types.ts.
 *
 * @example
 * import type { UserProfile, Project, PageSection } from "@syntaxure-labs/db/prisma-types";
 */

// Re-export all Prisma-generated types
export type {
  UserProfile,
  Client,
  Service,
  Project,
  Milestone,
  Quote,
  Invoice,
  CalendarEvent,
  CaseStudy,
  Feedback,
  Subscription,
  Notification,
  Invite,
  ContactMessage,
  WaitlistEntry,
  SupportTicket,
  Task,
  UserToken,
  AuditLog,
  SitePage,
  PageSection,
  Tag,
  QuoteService,
  TaskTag,
  ReleaseTag,
  CommunityPostTag,
  SupportTicketTag,
  Release,
  AvailabilitySlot,
  PricingPlan,
  PricingFaq,
  ProductTemplate,
  ContractTerm,
  CustomizationService,
  ClientContract,
  Workspace,
  WorkspaceMember,
  Department,
  WebhookEvent,
  CommunityMember,
  CommunityPost,
  CommunityInvite,
} from "@prisma/client";

// Re-export Prisma client instance
export { default as prisma } from "./prisma";
