/**
 * init command — the local onboarding path
 *
 * Zero network, zero account. Inspects the project's own package.json,
 * globals.css, and Tailwind config to generate a starter `.prism/rules.json`
 * (the same v1 shape `prism check` already parses and `prism pull` fetches
 * from the dashboard), then wires the Claude Code hooks (PreToolUse halt,
 * PostToolUse safety net, Stop gate) into `.claude/settings.json` so the
 * Pass starts enforcing immediately — plus Cursor/Antigravity JSON hooks
 * and the OpenCode plugin (`.opencode/plugin/prism.js`, throw-based
 * dispatch, no exit codes) as separate, additive targets.
 *
 * Never overwrites `.prism/rules.json` or any agent's existing hook file
 * without confirmation — see writeRulesFile(), wireClaudeHook(), and
 * wireOpenCodeHook() ("foreign" = left untouched).
 */

import chalk from "chalk";
import { existsSync, readFileSync } from "fs";
import { join } from "path";
import { atomicWriteFileSync } from "../util/atomic-write.js";
import { promptYesNo } from "../util/prompt.js";
import {
  detectProject,
} from "../init/detect.js";
import { extractTokens } from "../init/tokens.js";
import { generateRuleSet } from "../init/generate-rules.js";
import {
  wireAntigravityHook,
  wireClaudeHook,
  wireCursorHook,
  wireOpenCodeHook,
  type AgentWireResult,
} from "../init/hook.js";

export interface InitOptions {
  yes?: boolean;
  force?: boolean;
  /** Internal — lets tests point init() at a fixture directory instead of
   *  the real process.cwd(). Not exposed as a CLI flag. */
  cwd?: string;
}

export async function init(options: InitOptions = {}): Promise<void> {
  const cwd = options.cwd ?? process.cwd();
  console.log(chalk.bold("◈ Prism Context Engine — init\n"));
  console.log(chalk.dim("  Scanning this project. No network calls.\n"));

  const detection = detectProject(cwd);
  const tokens = await extractTokens(cwd);
  const ruleSet = generateRuleSet(detection, tokens);

  printDetection(detection);
  printTokens(tokens);

  const rulesPath = join(cwd, ".prism", "rules.json");
  const rulesWritten = await writeRulesFile(rulesPath, ruleSet, options);

  const hookResult = wireClaudeHook(cwd);
  printHookResult(hookResult);

  // Phase 4: Cursor + Antigravity wiring (best-effort, additive). Claude
  // Desktop has no hooks system — MCP advisory only, handled by ide-setup.
  for (const [agent, result] of [
    ["Cursor", wireCursorHook(cwd)],
    ["Antigravity", wireAntigravityHook(cwd)],
  ] as Array<[string, AgentWireResult]>) {
    printAgentHookResult(agent, result);
  }

  // OpenCode: its own plugin file (throw-based dispatch, auto-discovered —
  // no opencode.json entry), wired in parallel with the JSON-hook agents.
  const openCodeResult = wireOpenCodeHook(cwd);
  printAgentHookResult("OpenCode", openCodeResult);
  if (
    (openCodeResult.outcome === "created" ||
      openCodeResult.outcome === "already-present") &&
    !projectHasCli(cwd)
  ) {
    console.log(
      chalk.yellow(
        "⚠ The OpenCode plugin needs @prism-engine/cli in this project's package.json — until it's installed, the plugin fails open (no enforcement).",
      ),
    );
  }

  printSummary(ruleSet, rulesWritten, rulesPath);
}

/** Does this project's package.json declare @prism-engine/cli in any dep
 *  section? The generated OpenCode plugin imports it at session start. */
function projectHasCli(cwd: string): boolean {
  try {
    const pkg = JSON.parse(
      readFileSync(join(cwd, "package.json"), "utf8"),
    ) as Record<string, Record<string, unknown> | undefined>;
    for (const field of [
      "dependencies",
      "devDependencies",
      "peerDependencies",
      "optionalDependencies",
    ]) {
      if (pkg[field]?.["@prism-engine/cli"]) return true;
    }
  } catch {
    // No/unreadable package.json — same fail-open posture as the plugin.
  }
  return false;
}

function printAgentHookResult(
  agent: string,
  result: AgentWireResult,
): void {
  switch (result.outcome) {
    case "created":
      console.log(`${chalk.green("✓")} Created ${agent} hook (${result.path})`);
      break;
    case "merged":
      console.log(`${chalk.green("✓")} Merged Pass into existing ${agent} hooks`);
      break;
    case "already-present":
      console.log(`${chalk.green("✓")} ${agent} already has the Pass wired in`);
      break;
    case "invalid-json":
      console.log(
        chalk.yellow(`⚠ ${agent} config exists but isn't valid JSON — left untouched.`),
      );
      break;
    case "foreign":
      console.log(
        chalk.yellow(
          `⚠ ${agent} hook file exists but wasn't generated by Prism — left untouched.`,
        ),
      );
      break;
  }
}

function printDetection(detection: ReturnType<typeof detectProject>): void {
  if (!detection.hasPackageJson) {
    console.log(
      chalk.yellow("⚠ No package.json found — detection is limited.\n"),
    );
    return;
  }
  const parts: string[] = [];
  parts.push(
    detection.isNextjs
      ? `Next.js ${detection.nextVersion ?? ""}`.trim()
      : "Next.js: not detected",
  );
  if (detection.isNextjs) {
    const router =
      detection.router === "both"
        ? "app + pages routers"
        : detection.router === "none"
          ? "router not found"
          : `${detection.router} router`;
    parts.push(router);
  }
  parts.push(
    detection.hasTailwind
      ? `Tailwind ${detection.tailwindVersion ?? ""}`.trim()
      : "Tailwind: not detected",
  );
  if (detection.hasVue) parts.push("Vue");
  if (detection.hasSvelte) parts.push("Svelte");
  console.log(`Detected: ${chalk.cyan(parts.join(" · "))}\n`);
}

function printTokens(tokens: Awaited<ReturnType<typeof extractTokens>>): void {
  if (tokens.cssFilesScanned.length > 0) {
    console.log(
      `${chalk.green("✓")} Scanned ${tokens.cssFilesScanned.join(", ")}`,
    );
  } else {
    console.log(`${chalk.yellow("⚠")} No globals.css found in common locations`);
  }
  console.log(
    `${chalk.green("✓")} Found ${chalk.bold(String(tokens.colorTokens.length))} color token(s) as CSS custom properties`,
  );
  if (tokens.tailwindConfigFile) {
    const via = tokens.tailwindConfigParsedViaRegexFallback
      ? "regex fallback, best-effort"
      : "parsed directly";
    console.log(
      `${chalk.green("✓")} ${tokens.tailwindConfigFile} found (${via}) — ${tokens.tailwindConfigColorCount} theme color(s) (informational; enforced via the CSS token rule above, not directly)`,
    );
  }
  console.log("");
}

async function writeRulesFile(
  rulesPath: string,
  ruleSet: Awaited<ReturnType<typeof generateRuleSet>>,
  options: InitOptions,
): Promise<boolean> {
  const exists = existsSync(rulesPath);
  if (exists && !options.force) {
    let proceed: boolean;
    if (options.yes) {
      console.log(
        chalk.yellow(
          "⚠ .prism/rules.json already exists — leaving it untouched (pass --force to regenerate).",
        ),
      );
      proceed = false;
    } else {
      proceed = await promptYesNo(
        ".prism/rules.json already exists. Overwrite it with a freshly generated starter?",
        false,
      );
      if (!proceed) {
        console.log(chalk.dim("  Kept the existing .prism/rules.json.\n"));
      }
    }
    if (!proceed) return false;
  }

  atomicWriteFileSync(rulesPath, `${JSON.stringify(ruleSet, null, 2)}\n`);
  console.log(
    `${chalk.green("✓")} Wrote ${chalk.bold(String(ruleSet.rules.length))} rule(s) to .prism/rules.json`,
  );
  console.log("");
  return true;
}

function printHookResult(result: ReturnType<typeof wireClaudeHook>): void {
  switch (result.outcome) {
    case "created":
      console.log(
        `${chalk.green("✓")} Created .claude/settings.json with the Pass hooks wired in (PreToolUse + PostToolUse + Stop)`,
      );
      break;
    case "merged":
      console.log(
        `${chalk.green("✓")} Merged the Pass hooks into the existing .claude/settings.json`,
      );
      break;
    case "already-present":
      console.log(
        `${chalk.green("✓")} .claude/settings.json already has the Pass hooks wired in`,
      );
      break;
    case "invalid-json":
      console.log(
        chalk.yellow(
          "⚠ .claude/settings.json exists but isn't valid JSON — left it untouched. Add the hooks manually:",
        ),
      );
      console.log(
        chalk.dim(
          '  { "hooks": { "PreToolUse": [{ "matcher": "Write|Edit|MultiEdit", "hooks": [{ "type": "command", "command": "npx @prism-engine/cli check --hook --format claude-code" }] }],',
        ),
      );
      console.log(
        chalk.dim(
          '              "PostToolUse": [{ "matcher": "Write|Edit", "hooks": [{ "type": "command", "command": "npx @prism-engine/cli check --hook --format claude-code" }] }],',
        ),
      );
      console.log(
        chalk.dim(
          '              "Stop": [{ "hooks": [{ "type": "command", "command": "npx @prism-engine/cli check --hook --format claude-code" }] }] } }',
        ),
      );
      break;
  }
  console.log("");
}

function printSummary(
  ruleSet: Awaited<ReturnType<typeof generateRuleSet>>,
  rulesWritten: boolean,
  rulesPath: string,
): void {
  console.log(chalk.bold("Done.\n"));
  if (rulesWritten) {
    for (const rule of ruleSet.rules) {
      const kind = rule.check ? rule.check.type : "advisory-only";
      console.log(`  ${chalk.cyan("•")} ${rule.id} ${chalk.dim(`(${kind})`)}`);
    }
    console.log("");
  }
  console.log(chalk.dim(`  rules file: ${rulesPath}`));
  console.log(
    chalk.bold("\nNext: ") +
      "write or edit a file in this project — the hook runs automatically.",
  );
  console.log(
    chalk.dim(
      "  Or check by hand:  ",
    ) + chalk.cyan("prism check <file>"),
  );
  console.log(
    chalk.dim("  Team on the dashboard? Sync their rules:  ") +
      chalk.cyan("prism pull"),
  );
}
