/**
 * E2E Test Account Provisioner
 * ----------------------------
 * Creates (or resets) ONE real, disposable Supabase account dedicated to
 * automated testing — not a fake/bypassed login, a real account that just
 * isn't a person. Mirrors seed-founder.ts's pattern (Supabase admin API +
 * user_profiles + prism_subscriptions), but:
 *   - tier is "pro" (not "enterprise") — just enough to pass the ideSync
 *     gate that /api/mcp/stdio enforces (TIER_LIMITS.free.ideSync = false,
 *     so the MCP step of the E2E suite 403s on a free-tier account no
 *     matter how correct the migration is — this exists specifically to
 *     avoid that trap).
 *   - the password is random per run unless you pin one via
 *     E2E_TEST_PASSWORD, and gets written to a gitignored .env.e2e.local
 *     instead of a fixed value in source.
 *   - `--delete` tears the account down again when you're done with it.
 *
 * Run:
 *   dotenv -e .env.local -- tsx scripts/create-e2e-test-user.ts
 *   dotenv -e .env.local -- tsx scripts/create-e2e-test-user.ts --delete
 *
 * Needs NEXT_PUBLIC_SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY for whichever
 * environment you're testing (same vars prism-engine already needs) —
 * these are secrets, keep them out of chat/commits, load them from your
 * own .env.local / Doppler / CI secret store.
 */

import { createClient } from "@supabase/supabase-js";
import { getPrismDb } from "@syntaxure-labs/db/prism";
import { randomBytes } from "crypto";
import { writeFileSync } from "fs";
import { resolve } from "path";

const EMAIL = process.env.E2E_TEST_EMAIL || "e2e-test@prism.syntaxure.dev";
const PASSWORD =
  process.env.E2E_TEST_PASSWORD || `E2e-${randomBytes(12).toString("base64url")}!`;
const SHOULD_DELETE = process.argv.includes("--delete");

async function main() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    console.error(
      "❌ Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.",
    );
    process.exit(1);
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const { data: existingUsers, error: listError } =
    await supabase.auth.admin.listUsers();
  if (listError) throw listError;
  const existing = existingUsers?.users.find((u) => u.email === EMAIL);

  if (SHOULD_DELETE) {
    if (!existing) {
      console.log(`ℹ️  No account found for ${EMAIL} — nothing to delete.`);
      return;
    }
    const { error } = await supabase.auth.admin.deleteUser(existing.id);
    if (error) throw error;
    // user_profiles / prism_subscriptions cascade on delete (FK ON DELETE CASCADE)
    console.log(`🗑️  Deleted E2E test account ${EMAIL} (${existing.id}).`);
    return;
  }

  console.log(`🚀 Provisioning E2E test account: ${EMAIL}`);

  let userId: string;
  if (existing) {
    console.log("👤 Account already exists — resetting its password...");
    const { data, error } = await supabase.auth.admin.updateUserById(
      existing.id,
      { password: PASSWORD },
    );
    if (error) throw error;
    userId = data.user.id;
  } else {
    console.log("👤 Creating new account...");
    const { data, error } = await supabase.auth.admin.createUser({
      email: EMAIL,
      password: PASSWORD,
      email_confirm: true, // skip the email verification loop — this is an admin-provisioned test account
      user_metadata: { full_name: "E2E Test Account" },
    });
    if (error) throw error;
    userId = data.user.id;
  }
  console.log(`✅ Auth account ready (${userId})`);

  await supabase.from("user_profiles").upsert(
    {
      id: userId,
      email: EMAIL,
      full_name: "E2E Test Account",
      role: "client",
      tier: "pro",
      updated_at: new Date().toISOString(),
    },
    { onConflict: "id" },
  );
  console.log("✅ user_profiles row set (tier: pro)");

  const db = getPrismDb();
  const now = new Date();
  const oneYearOut = new Date(now.getFullYear() + 1, now.getMonth(), now.getDate());

  const { error: subError } = await db.from("prism_subscriptions").upsert(
    {
      user_id: userId,
      tier: "pro", // must be at least "pro" — /api/mcp/stdio 403s on free tier
      status: "active",
      current_period_start: now.toISOString(),
      current_period_end: oneYearOut.toISOString(),
      metadata: { isE2ETestAccount: true },
      updated_at: now.toISOString(),
    },
    { onConflict: "user_id" },
  );
  if (subError) throw subError;
  console.log("✅ prism_subscriptions row set (tier: pro, status: active)");

  const envFile = resolve(__dirname, "..", ".env.e2e.local");
  writeFileSync(
    envFile,
    [
      "# Generated by scripts/create-e2e-test-user.ts — DO NOT COMMIT",
      `E2E_TEST_EMAIL=${EMAIL}`,
      `E2E_TEST_PASSWORD=${PASSWORD}`,
      "",
    ].join("\n"),
  );

  console.log(`\n🎉 E2E test account ready.`);
  console.log(`   Email:    ${EMAIL}`);
  console.log(`   Password: (written to ${envFile}, not printed here)`);
  console.log(`\nRun the suite with:`);
  console.log(
    `   dotenv -e .env.e2e.local -e .env.local -- pnpm --filter prism-engine run test:e2e`,
  );
  console.log(`\nTear it down when you're done:`);
  console.log(
    `   dotenv -e .env.local -- tsx scripts/create-e2e-test-user.ts --delete`,
  );
}

main().catch((error) => {
  console.error("❌ Error:", error);
  process.exit(1);
});
